version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm install 
  build:
    - npm run build
    - npm run cdk --synth

artifact:
  base-directory: cdk.out
  files:
  - '**/*'